CREATE SEQUENCE IF NOT EXISTS mfa_grouping_read_seq START 10001;

CREATE TABLE IF NOT EXISTS MFA_GROUPING
(
    MFA_GROUPING_NUMBER		VARCHAR(255)	PRIMARY KEY DEFAULT 'MFA' || NEXTVAL('mfa_grouping_read_seq') NOT NULL,
    GA_ID				    NUMERIC			REFERENCES GRANTING_AUTHORITY(GA_ID) NOT NULL,
    MFA_GROUPING_NAME       VARCHAR(255)    NOT NULL,
    CREATED_BY			    VARCHAR(255)	DEFAULT 'SYSTEM',
    STATUS				    VARCHAR(255)	DEFAULT 'DRAFT',
    CREATED_TIMESTAMP		TIMESTAMP 		WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_TIMESTAMP	TIMESTAMP		WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    DELETED_BY			    VARCHAR(255),
    DELETED_TIMESTAMP       TIMESTAMP 		WITHOUT TIME ZONE
);