CREATE SEQUENCE IF NOT EXISTS mfa_grouping_read_seq START 10001;

CREATE SEQUENCE IF NOT EXISTS mfa_award_read_seq START 1;

CREATE TABLE IF NOT EXISTS MFA_GROUPING
(
    MFA_GROUPING_NUMBER		VARCHAR(255)	PRIMARY KEY DEFAULT 'MFA' || NEXTVAL('mfa_grouping_read_seq') NOT NULL,
    GA_ID				    NUMERIC			REFERENCES GRANTING_AUTHORITY(GA_ID) NOT NULL,
    MFA_GROUPING_NAME       VARCHAR(255)    NOT NULL,
    CREATED_BY			    VARCHAR(255)	DEFAULT 'SYSTEM',
    STATUS				    VARCHAR(255)	DEFAULT 'DRAFT',
    CREATED_TIMESTAMP		TIMESTAMP 		WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_TIMESTAMP	TIMESTAMP		WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    DELETED_BY			    VARCHAR(255),
    DELETED_TIMESTAMP       TIMESTAMP 		WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS MFA_AWARD
(
    MFA_AWARD_NUMBER		NUMERIC         PRIMARY KEY DEFAULT NEXTVAL('mfa_award_read_seq') NOT NULL,
    IS_SPEI                 BOOLEAN         NOT NULL,
    HAS_MFA_GROUPING        BOOLEAN         NOT NULL,
    MFA_GROUPING_NUMBER		VARCHAR(255)	REFERENCES MFA_GROUPING(MFA_GROUPING_NUMBER),
    AWARD_AMOUNT            NUMERIC(36,2)   NOT NULL,
    CONFIRMATION_DATE       DATE            NOT NULL,
    PUBLISHED_DATE          DATE,
    GA_ID				    NUMERIC			REFERENCES GRANTING_AUTHORITY(GA_ID) NOT NULL,
    RECIPIENT_NAME          VARCHAR(255)    NOT NULL,
    RECIPIENT_ID_TYPE       VARCHAR(255)    NOT NULL,
    RECIPIENT_ID            VARCHAR(255)    NOT NULL,
    STATUS				    VARCHAR(255)	DEFAULT 'DRAFT' NOT NULL,
    CREATED_BY			    VARCHAR(255)	DEFAULT 'SYSTEM' NOT NULL,
    APPROVED_BY             VARCHAR(255),
    REASON                  VARCHAR(1000),
    CREATED_TIMESTAMP		TIMESTAMP 		WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_MODIFIED_TIMESTAMP	TIMESTAMP		WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED_BY			    VARCHAR(255),
    DELETED_TIMESTAMP       TIMESTAMP 		WITHOUT TIME ZONE
);